blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord
    url: https://discord.gg/kqNCe2D
    about: A place to discuss and collaborate with other Homebridge users and developers.
  - name: Homebridge Reddit
    url: https://www.reddit.com/r/homebridge/
    about: A place to discuss Homebridge, get help with it, ask questions about it, post plugins, and more.
