name: CI

on:
  push:
    # tags:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version (git tag)
      id: get_version
      run: |
        echo ${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Setup Toolchain
      run: |
        sudo -E ./.ci/setup-toolchain.sh

    - name: Build Package
      run: |
        sudo -E ./.ci/build-package.sh
      env:
        SPK_PACKAGE_VERSION: ${{ steps.get_version.outputs.VERSION }}