name: CI

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - SPK_PLATFORM: braswell
            SPK_ARCH: x86_64
          - SPK_PLATFORM: rtd1296
            SPK_ARCH: armv8

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the upload URL for a release
      id: get_release
      uses: bruceadams/get-release@v1.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the version (git tag)
      id: get_version
      run: |
        echo ${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Setup Toolchain
      run: |
        sudo -E ./.ci/setup-toolchain.sh
      env:
        SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}

    - name: Build Package
      run: |
        sudo -E ./.ci/build-package.sh
      env:
        SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}
        SPK_ARCH: ${{ matrix.SPK_ARCH }}
        SPK_PACKAGE_VERSION: ${{ steps.get_release.outputs.tag_name }}

    - name: Upload SPK To Release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./homebridge-${{ matrix.SPK_PLATFORM }}-${{ steps.get_release.outputs.tag_name }}.spk
        asset_name: homebridge-${{ matrix.SPK_PLATFORM }}-${{ steps.get_release.outputs.tag_name }}.spk
        asset_content_type: application/octet-stream